### ISSUE TITLE
Specifying version of scipy to <=1.8 means I cant use dtwParallel in my project

### ISSUE THREAD

**Issue by jonathanstathakis** [oscarescuderoarnanz/dtwParallel#4]
I am curious why this is, I was excited to integrate your package into my project however the dependency version conflict makes this untenable, especially as scipy==1.7.3 requires Python < 3.11. Any chance this was an oversight?

**Comment by oscarescuderoarnanz** [comment]
Thank you very much for your message @jonathanstathakis . After verifying the correct operation by removing the restriction, I have proceeded to update the package version to 0.9.39 with the scipy restriction removed. I hope to have solved your problem, I remain attentive to any other inconvenience. Thank you very much. 

I add the version with which I have run the different experiments: 
- scipy: 1.8.0
- Python: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
