### ISSUE TITLE
Error when using Euclidean distance as local_disimilarity in univariate DTW

### ISSUE THREAD

**Issue by jongwonKim-1997** [oscarescuderoarnanz/dtwParallel#5]
I'm currently using the package and it's working great. However, when I compute the DTW for univariate time series using the Euclidean distance as an argument for local_disimilarity, I encounter the following error:

<img width="634" alt="dtw" src="https://github.com/oscarescuderoarnanz/dtwParallel/assets/77820101/06baac4f-22b0-4a2c-a8e7-4809e4794f98">

I would truly appreciate it if this issue could be resolved!

**Comment by jongwonKim-1997** [comment]
Additionally, it would be great if there is an argument to decide whether to return the warping path between two time series.

**Comment by oscarescuderoarnanz** [comment]
@jongwonKim-1997, could you tell me what version of scipy you have installed?
I have tested that same example with scipy: 1.8.0 & Python: 3.8.10.

**Comment by jongwonKim-1997** [comment]
> @jongwonKim-1997, could you tell me what version of scipy you have installed? I have tested that same example with scipy: 1.8.0 & Python: 3.8.10.

I ran the code on Colab and it also did not work on my local computer. The respective scipy versions are 1.11.2 and 1.10.1.

Fortunately, after reinstalling with the scipy version 1.8.1 you mentioned, it worked.

**Comment by oscarescuderoarnanz** [comment]
Great @jongwonKim-1997 , I'm happy to assist you with anything else. I will be publishing a new version soon, which will include the ability to calculate the path between two-time series.
