### ISSUE TITLE
Input vector should be 1-D.

### ISSUE THREAD

**Issue by lenacypris** [oscarescuderoarnanz/dtwParallel#6]
I wanted to try out your package but even the first error result in the following error code. Do you know how I can fix this?

from dtwParallel import dtw_functions
from scipy.spatial import distance as d

# For Univariate Time Series
x = [1,2,3]
y = [0,0,1]

dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)

*************************************************************************
[5] x = [1,2,3]
      [6] y = [0,0,1]
----> [8]dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)

File [c:\Anaconda\envs\master_thesis\lib\site-packages\dtwParallel\dtw_functions.py:514](file:///C:/Anaconda/envs/master_thesis/lib/site-packages/dtwParallel/dtw_functions.py:514), in dtw(ts1, ts2, type_dtw, constrained_path_search, local_dissimilarity, MTS, get_visualization, check_errors, regular_flag, n_threads, dtw_to_kernel, sigma_kernel, itakura_max_slope, sakoe_chiba_radius, term_exec)
    510                 return dtw_distance, transform_dtw_to_kernel(dtw_distance, sigma_kernel)
    512         # In case of having 2 UTS.
    513         else:
--> 514             dtw_distance, cost_matrix = dtw_dep(ts1, ts2, local_dissimilarity, mask)
    517 if get_visualization and not MTS:
    518     if type_dtw == "i":

File [c:\Anaconda\envs\master_thesis\lib\site-packages\dtwParallel\dtw_functions.py:369](file:///C:/Anaconda/envs/master_thesis/lib/site-packages/dtwParallel/dtw_functions.py:369), in dtw_dep(ts1, ts2, local_dissimilarity, mask, mult_uts, regular_flag)
    367         for j in range(len_ts2):
    368             if np.isfinite(mask[i, j]):
--> 369                 cost_matrix[i + 1, j + 1] = local_dissimilarity(ts1[i], ts2[j])
    370                 cost_matrix[i + 1, j + 1] += min(cost_matrix[i, j + 1],
    371                                        cost_matrix[i + 1, j],
    372                                        cost_matrix[i, j])
    374 if mult_uts:

File [c:\Anaconda\envs\master_thesis\lib\site-packages\scipy\spatial\distance.py:536](file:///C:/Anaconda/envs/master_thesis/lib/site-packages/scipy/spatial/distance.py:536), in euclidean(u, v, w)
...
    316 if u.ndim == 1:
    317     return u
--> 318 raise ValueError("Input vector should be 1-D.")

ValueError: Input vector should be 1-D.

**Comment by oscarescuderoarnanz** [comment]
Hi @lenacypris , I apologize for the error. Which version of SciPy do you have installed? I've tested the example with SciPy 1.8.0 and Python 3.8.10. Please try testing it with the specified version of SciPy. If the error persists, please don't hesitate to let me know.

Thank you very much
