### ISSUE TITLE
Can dtwParallel align two multivariate sequences of keypoints with x and y coordinates in time?

### ISSUE THREAD

**Issue by jackhawa** [oscarescuderoarnanz/dtwParallel#8]
For example aligning two separate sequences of body keypoints of two baseball players swinging a bat.

**Comment by oscarescuderoarnanz** [comment]
Hi @jackhawa, the code that implements dtwParallel does not allow that computation. However, if it would be possible to address that particular example with some modifications to the current code. If you are interested we could discuss it in more detail.

Thanks. Regards,
Oscar.

**Comment by jackhawa** [comment]
Hey @oscarescuderoarnanz , I was able to find an alternative library (tslearn) that allows me to do that and I have gotten good results.
