### ISSUE TITLE
Computing dtw on multivariate time series with type_dtw="i"

### ISSUE THREAD

**Issue by SebastianSchmalzer** [oscarescuderoarnanz/dtwParallel#9]
I want to run dtw on multivariate time series (possibly the time series have different lengths) with type_dtw=“i”, as in the following example, which considers two two-dimensional time series (one of length 4 and the other one of length 3):

```
from dtwParallel import dtw_functions
import numpy as np

ts1 = np.array([
    [3., 1.],
    [4., 5.],
    [1., 5.],
    [1., 3.],
])
ts2 = np.array([
    [2., 1.],
    [3., 2.],
    [1., 2.],
])

dtw_functions.dtw(ts1, ts2, MTS=True, type_dtw="i")
```

According to the papers, I would expect the algorithm to run through each dimension and perform dtw for univariate time series between ts1 and ts2. As a final dtw score, I would expect the sum of the dtw scores in all dimensions. Am I right about this?

However the example above fails because of 
`ValueError: operands could not be broadcast together with shapes (4,) (3,)`
Am I using the wrong input format or am I missing something else?

**Comment by oscarescuderoarnanz** [comment]
Hello @sebastianschmalzer, your format is correct, I will solve the problem in the next few days, this Sunday at the latest.

**Comment by oscarescuderoarnanz** [comment]
Hello @sebastianschmalzer, as they are time series of different dimensions you have to indicate it to the algorithm, so please complete the time series with a flag value of your choice, for example, 666, and indicate it in the call. This way you will have the right behavior. I have attached the example. 
  ```
import dtw_functions
import numpy as np

ts1 = np.array([
    [3., 1.],
    [4., 5.],
    [1., 5.],
    [1., 3.],
])
ts2 = np.array([
    [2., 1.],
    [3., 2.],
    [1., 2.],
    [666, 666],
])

dtw_functions.dtw(ts1, ts2, MTS=True, regular_flag=666, type_dtw="i")
  ```
Thank you very much and sorry for the delay.

**Comment by SebastianSchmalzer** [comment]
Hello @oscarescuderoarnanz, thank you for your quick response. 
In my opinion, the problem lies somewhere else. As mentioned, independent m-dimensional DTW corresponds to performing m univariate DTW and summing up their cost matrices or scores. The different dimensions in this example correspond to different lengths of the time series and (univariate) DTW for two time series of different lengths is not a problem.

![dtw_ind](https://github.com/user-attachments/assets/e6c7de27-e6b0-444f-a50e-d2de3b92e160)

In my point of view, the problem could be solved if line 313 in the function `dtw_ind` of file `dtw_functions.py` would be changed from 
`cost_matrix[i + 1, j + 1] = local_dissimilarity(ts1_aux, ts2_aux)`
to 
`cost_matrix[i + 1, j + 1] = local_dissimilarity(ts1_aux[i], ts2_aux[j])`.

Because currently, `local_dissimilarity` is computed over the whole dimension (i.e. over a whole univariate time series) and summed up in each entry of the cost matrix.
For example, if 

> local_dissimilarity(ts1_aux, ts2_aux) = dist

then the cost_matrix would look like

```
[[ 1*dist, 2*dist, 3*dist, 4*dist, ...],
 [ 2*dist, 2*dist, 3*dist, 4*dist, ...],
 [ 3*dist, 3*dist, 3*dist, 4*dist, ...],
 [ 4*dist, 4*dist, 4*dist, 4*dist, ...],
 ... ]
```

 
 Can you understand my request?

**Comment by oscarescuderoarnanz** [comment]
Hi @sebastianschmalzer, everything you have said is correct, you are right. I have tested the approach you gave me and it is correct, would you like to make a pull request since you have detected it?

Thank you very much. 
Best regards,
Oscar.
